### ISSUE TITLE
Can't find module named 'pomdp_py.algorithms.po_uct'

### ISSUE THREAD

**Issue by JellaGit** [h2r/pomdp-py#24] opened 2023-01-04 11:58 UTC
Hi all & happy new year,

I tried installing this version(1.3.2) of the pomdp_py 

I followed the instructions on how to install pomdp_py via https://h2r.github.io/pomdp-py/html/installation.html .
So I did the following in my Anaconda prompt (Anaconda3) :

1. Install Cython: pip install Cython
2. Download the packages from this GitHub page : Source code (zip) Apr 3, 2022 and Source code (tar.gz) Apr 3, 2022
3. pip install -e .

This all seemed to work.

Then I tried to test things out:
python -m pomdp_py -r tiger
python -m pomdp_py -r rocksample
python -m pomdp_py -r mos

But for all, the error my Anaconda Prompt gives is :
ModuleNotFoundError: No module named 'pomdp_py.algorithms.po_uct'

I also tried it directly from Spyder(5.3.3), but got the same result.
\pomdp_py\utils\debugging.py", line 91, in <module>
    from pomdp_py.algorithms.po_uct import TreeNode, QNode, VNode, RootVNode
ModuleNotFoundError: No module named 'pomdp_py.algorithms.po_uct'

Does anyone know where I go wrong or how to fix it?

Sorry if it is foolish, I never download packages.

**Comment by zkytony** [comment] 2023-01-04 12:08
Thanks for posting! It is great that you tried and shared your experience.

I can't immediately tell what the cause is in your case, but the symptom is the po_uct's Cython files don't seem to be found (e.g. pomdp_py.algorithms.po_uct points to [pomdp_py/algorithms/po_uct.pyx](https://github.com/h2r/pomdp-py/blob/master/pomdp_py/algorithms/po_uct.pyx)).

After completing step 3, can you just try
```
import pomdp_py
``` 
in a Python shell?

**Comment by JellaGit** [comment] 2023-01-04 12:54
Running only import pomdp_py does not give errors.

**Comment by zkytony** [comment] 2023-01-04 13:13
What about the following
```python
from pomdp_py import POUCT
```
Also, do you see the presence of `.pyx` and `.pxd` files in your decompressed folder of pomdp-py?

**Comment by JellaGit** [comment] 2023-01-04 13:14
Still works

**Comment by zkytony** [comment] 2023-01-04 13:16
Interesting, what about doing the following:
```
>>> import pomdp_py
>>> pomdp_py.POUCT
<class 'pomdp_py.algorithms.po_uct.POUCT'>
>>> pomdp_py.POMCP
<class 'pomdp_py.algorithms.pomcp.POMCP'>
```

**Comment by zkytony** [comment] 2023-10-31 14:43
Closing this now. Feel free to reopen if this is still an issue.

**Closed by zkytony** 2023-10-31 14:43 UTC
